### ISSUE TITLE
'tccdefs.h' not found when running C demo

### ISSUE THREAD

**Issue by andy5995** [KaruroChori/vs-fltk#20] opened 2024-11-28 06:37 UTC
When I run the C demo:

```
builder@06ebe0448b27:/workspace$ ./build/vs run examples/demo-c.xml 
Policy-------------
headless:          0
verbosity:         1
networking.http:   1
networking.https:  1
networking.gemini: 1

--------- paths ---------
cwd:  file:///workspace/
app:  file:///workspace/examples/demo-c.xml
vs:   file:///workspace/commons/
data: file:///home/builder/.vs-fltk/
repo: file:///home/builder/.vs-fltk/packages/
tmp:  file:///tmp/
XML [file:///home/builder/.vs-fltk/default.xml] parsed with errors, attr value: []
Error description: File was not found
Error offset: 0

Loading embedded profile instead


[INFO]     : Requested loading of file `file:///workspace/examples/demo-c.xml`
[WARNING]  : Unable to use property `xmlns:fl` on  @ [/app]
[TCC]      : In file included from ./bindings/native/src/commons.c:0:
<command line>:13: error: include file 'tccdefs.h' not found @ [/app/fl:window/script]
[TCC]      : In file included from ./bindings/native/src/stub.c:0:
<command line>:13: error: include file 'tccdefs.h' not found @ [/app/fl:window/script]
[TCC]      : In file included from <string>:0:
<command line>:13: error: include file 'tccdefs.h' not found @ [/app/fl:window/script]
```

**Comment by KaruroChori** [comment] 2024-11-28 12:27
The command `vs` when run in that way after a build requires a prefix passed as env variable (this variable once installed will be either automatically guessed or put in .bashrc)

```
VS_COMMONS_DIR=$(pwd)/build/commons/ ./build/vs run examples/demo-c.xml
```

**Comment by KaruroChori** [comment] 2024-11-28 13:56
That is strange it would work regardless. Might I ask you to fully delete your build folder and do it again? I probably will need to fix some issues in the meson file.

**Comment by andy5995** [comment] 2024-11-28 22:27
I've deleted the build directory and pulled the latest code (I'm at 4fdb809) and rebuilt.

```
        bun run codegen
        bun run meson-setup.clang-release
        meson compile -C build/ vs:executable
```

## Without the variable

```builder@06ebe0448b27:/workspace$ ./build/vs run examples/demo-c.xml 
Policy-------------
headless:          0
verbosity:         1
networking.http:   1
networking.https:  1
networking.gemini: 1

--------- paths ---------
cwd:  file:///workspace/
app:  file:///workspace/examples/demo-c.xml
vs:   file:///workspace/commons/
data: file:///home/builder/.vs-fltk/
repo: file:///home/builder/.vs-fltk/packages/
tmp:  file:///tmp/
XML [file:///home/builder/.vs-fltk/default.xml] parsed with errors, attr value: []
Error description: File was not found
Error offset: 0

Loading embedded profile instead


[INFO]     : Requested loading of file `file:///workspace/examples/demo-c.xml`
[WARNING]  : Unable to use property `xmlns:fl` on  @ [/app]
[TCC]      : In file included from ./bindings/native/src/commons.c:0:
<command line>:13: error: include file 'tccdefs.h' not found @ [/app/fl:window/script]
[TCC]      : In file included from ./bindings/native/src/stub.c:0:
<command line>:13: error: include file 'tccdefs.h' not found @ [/app/fl:window/script]
[TCC]      : In file included from <string>:0:
<command line>:13: error: include file 'tccdefs.h' not found @ [/app/fl:window/script]builder@06ebe0448b27:/workspace$
```

### From the build directory

```
builder@06ebe0448b27:/workspace/build$ ./vs run ../examples/demo-c.xml 
Policy-------------
headless:          0
verbosity:         1
networking.http:   1
networking.https:  1
networking.gemini: 1
builder@06ebe0448b27:/workspace/build$ 
```


## With the variable



```
builder@06ebe0448b27:/workspace$ VS_COMMONS_DIR=$(pwd)/build/commons/ ./build/vs run examples/demo-c.xml 
Policy-------------
headless:          0
verbosity:         1
networking.http:   1
networking.https:  1
networking.gemini: 1

--------- paths ---------
cwd:  file:///workspace/
app:  file:///workspace/examples/demo-c.xml
vs:   file:///workspace/build/commons/
data: file:///home/builder/.vs-fltk/
repo: file:///home/builder/.vs-fltk/packages/
tmp:  file:///tmp/
XML [file:///home/builder/.vs-fltk/default.xml] parsed with errors, attr value: []
Error description: File was not found
Error offset: 0

Loading embedded profile instead


[INFO]     : Requested loading of file `file:///workspace/examples/demo-c.xml`
[WARNING]  : Unable to use property `xmlns:fl` on  @ [/app]
[INFO]     : Registering public callback symbol `on_add` @ [/app/fl:window/script]
[INFO]     : Registering public callback symbol `on_dec` @ [/app/fl:window/script]
[TCC]      : <string>:3: error: expression expected before '<eof>' @ [/app/fl:window/fl:button/script]builder@06ebe0448b27:/workspace$ 
```

### From the build directory

```
builder@06ebe0448b27:/workspace/build$ VS_COMMONS_DIR=$(pwd)/commons/ ./vs run ../examples/demo-c.xml 
Policy-------------
headless:          0
verbosity:         1
networking.http:   1
networking.https:  1
networking.gemini: 1
builder@06ebe0448b27:/workspace/build$ 
```

**Comment by KaruroChori** [comment] 2024-11-28 22:49
Case 2 should be fixed once your forcefully update libtcc in the subprojects. I fixed that specific bug in it two or three days ago.

**Comment by KaruroChori** [comment] 2024-11-28 22:58
As for case one, the error is "correct" in the sense that there is no such file in `file:///workspace/commons/` only in `file:///workspace/build/commons/` and the final installed `commons` directory.
I need to check the logic behind it, because it is behaving differently on different systems.

**Closed** 2024-11-30 03:29 UTC

**Comment by andy5995** [comment] 2024-12-05 16:48
After starting a new docker container, I have run into the problem again that I originally reported.

After 20 minutes of writing this ticket and trying some things, I found the problem is fixed when the commons dir ends with a '/'

**Comment by KaruroChori** [comment] 2024-12-05 20:14
This issue is strictly related to the specs & implementation of the function in `https://github.com/KaruroChori/vs-fltk/pull/21`.  
It is intended behaviour due to an internal convention for paths being used as base, and generated by the normalizer:
- Paths ending with `/` are normalized paths where the last token is a directory
- Paths not ending with `/` are normalized paths where the last token is a file (which can be stripped in several cases)
Even if a bit annoying, this is generally fine as users are not allowed to inject paths from the outside.  
However I did an exception for some injected values via env variables.  
Yet, paths injected via those variables must follow those same rules to work properly. 

As they are user-facing, either this has to be well documented, or I should have a more tolerant sanitation for env variables to prevent situations like this one.

**Comment by andy5995** [comment] 2024-12-07 07:07
I tried this, but the trailing slash gets truncated automatically:

```
meson.add_devenv(
    {
        'VS_COMMONS_DIR': 'meson.project_source_root()/build/commons/'),
    },
)
```

>As they are user-facing, either this has to be well documented, or I should have a more tolerant sanitation for env variables to prevent situations like this one.

It might be time to open a separate discussion or issue for this.

@Jammyjamjamman and I worked on #42 today and the poor bloke kept having to set the variable each time we restarted the container (I finally realized we could just add it to entry-main.sh, but by then it was time for me to go to bed).

As far as documenting it, in addition to that, we might add it to a message that gets output after meson runs: https://mesonbuild.com/Reference-manual_functions.html#message

When working with paths, I always truncate trailing slashes from any path. I thought that's the standard, best practice, to help avoid strings with '//' and any other things that could make things confusing. But I don't know your app well enough to understand why you chose not to do that, so I'm open to the idea that having trailing slashes is not always a bad thing and willing to brainstorm ideas or cause you headaches by finding problems.

Some vars could get exported easily enough by adding them to docker/entry-common.sh (and that may be a good temporary solution), but of course that would only be of value when using the container. What's needed is a single thing where they are only set in one place.

Another idea I had was have the app set them automatically when it is run from the build directory. But that's a silly idea because the whole purpose of env vars is so the app can do things based on them. It would probably make more sense for the app to check if the trailing slash is present, and if not, append it.

**Comment by KaruroChori** [comment] 2024-12-07 07:56
> As far as documenting it, in addition to that, we might add it to a message that gets output after meson runs: https://mesonbuild.com/Reference-manual_functions.html#message

Good idea!

> When working with paths, I always truncate trailing slashes from any path. I thought that's the standard, best practice, to help avoid strings with '//' and any other things that could make things confusing. But I don't know your app well enough to understand why you chose not to do that, so I'm open to the idea that having trailing slashes is not always a bad thing and willing to brainstorm ideas or cause you headaches by finding problems.

For context, `VS_COMMONS_DIR` is meant to be set in `/etc/environment` or equivalent when installing `vs` on your machine. It can be overridden for specific cases, but in general it will never be touched ever again.  

As the docker container is used for development, it is perfectly valid to add it to ` docker/entry-common.sh` in my opinion.  

In general, I agree with you; in the context of a normal filesystem, I also avoid trailing slashes.  
Still, this is not always the case nor possible.   
For example `https://hello.world/page` & `https://hello.world/page/` intended as URLs are not the same, unless your web server is purposefully enforcing that.   
To be fair, not even `..` and `.` would be resolved without some form of path normalization enabled.  

In vs, paths are not just used to match files on the filesystem.   
There are many virtual paths types like `repo://path/1` or `app://examples/hello.xml` and a well-defined set of rules on which physical resource to look for in case the previous attempt failed.  
As not all paths are just resolved on a typical filesystem, but they also involve network fetches, I wanted to preserve the distinction between file and folder with the trailing `/`.  
However `/////` are collapsed into `/` and `..` `.` are all resolved as part of the normalization, and to ensure scoping when using virtual paths like `this://`.  

All this is mostly invisible to the final user, we just ended up with a function being repurposed because of my lazyness, and some input which is not conforming to its tight expectations :).

**Comment by andy5995** [comment] 2024-12-11 08:56
> > As far as documenting it, in addition to that, we might add it to a message that gets output after meson runs: https://mesonbuild.com/Reference-manual_functions.html#message
> 
> Good idea!
> 
> > When working with paths, I always truncate trailing slashes from any path. I thought that's the standard, best practice, to help avoid strings with '//' and any other things that could make things confusing. But I don't know your app well enough to understand why you chose not to do that, so I'm open to the idea that having trailing slashes is not always a bad thing and willing to brainstorm ideas or cause you headaches by finding problems.
> 
> For context, `VS_COMMONS_DIR` is meant to be set in `/etc/environment` or equivalent when installing `vs` on your machine. It can be overridden for specific cases, but in general it will never be touched ever again.
> 

Please let me know if you ever decide to go the route of a config file. I'll offer to add support for one of my projects: https://github.com/andy5995/canfigger/ wink wink

**Comment by KaruroChori** [comment] 2024-12-11 10:05
I saw it :D. Sadly being gpl3.0 it would not be compatible with the licences used by `vs`.  

Aside from licensing, there is a good reason to use XML for most configuration within this project.
`vs.tmpl` takes XML (data) as input and generates XML (vs ui) as output based on a template... so I just need to define such template, and for free I get that `vs` can show it and edit its own configuration files within a UI.  

The same approach will be used to present documentation from schemas, the component inspector of the internal editor/debugger etc...  that is why everything is planned to be XML (and markdown) :D.
